
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'rightIDMODULErightIGUALrightUPDATErightNUMEROleftNOIGUALleftMENORQMAYORQleftSUMARESTAleftMULTIDIVrightPUNTOleftPIZQPDERleftLLIZQLLDERARGS AS BOOLEAN CONSOLE DATETIME DIM DIV END FALSE ID IGUAL IMPORTS LLDER LLIZQ MAIN MAYORQ MENORQ MOD MODULE MULTI NOIGUAL NOW NUMERO PDER PIZQ PROGRAM PUNTO READKEY READLINE RESTA STRING SUB SUMA TRUE UPDATE VBCRLF WRITELINEempty : '
    
_lr_action_items = {'$end':([0,1,],[-1,0,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'empty':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> empty","S'",1,None,None,None),
  ('empty -> <empty>','empty',0,'p_empty','analizadorSintacticoVBALL.py',30),
]
